### ISSUE TITLE
Codigo c++

### ISSUE THREAD

**Issue by PazSoriano2tm27** [rod00001/grafc#1]
#include <iostream>
#include <cmath>
using namespace std;
int main () {
float X= 0;
float Y= 0;
float teta= 0;
float r= 0;  
teta=atan(Y/X);
r=sqrt((X*X)+(Y*Y)); 
cout<<"("<<r<<","<<teta<<")"<<endl;
}

**Comment by rod00001** [comment]
ok

**Comment by PazSoriano2tm27** [comment]
Le envío todos los códigos que hicimos?

**Comment by rod00001** [comment]
Crea un repositorio y ahí ponlos.

**Comment by PazSoriano2tm27** [comment]
Como se crea eso Ahaha ya le estuve intentando 😭

**Comment by rod00001** [comment]
Crea un repositorio y ahí los pones

**Comment by rod00001** [comment]
https://docs.github.com/es/get-started/quickstart/create-a-repo
ese es un tutorial

**Comment by PazSoriano2tm27** [comment]
Si ya me enseñaron como en un rato lo subo bien

**Comment by rod00001** [comment]
ayer era el dia de subir
